name: Continuous Integration
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

permissions:
  actions: read
  contents: read

jobs:
  pre-commit:
    name: Validation
    uses: stellarcyber-core/actions/.github/workflows/validation.yaml@main
    with:
      runDefaultLinters: false
      runDefaultTests: false
    secrets:
      GIT_TOKEN_BASIC: ${{ secrets.GIT_TOKEN_BASIC }}

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GIT_TOKEN_BASIC }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npx cypress install
      - uses: nrwl/nx-set-shas@v4
      - run: npx nx affected -t lint test build e2e
